#!/bin/sh

giftmp=/tmp/outXXXXXXXXXX.gif

unset x y w h
eval $(xwininfo |
sed -n -e "s/^ \+Absolute upper-left X: \+\([0-9]\+\).*/x=\1/p" \
    -e "s/^ \+Absolute upper-left Y: \+\([0-9]\+\).*/y=\1/p" \
    -e "s/^ \+Width: \+\([0-9]\+\).*/w=\1/p" \
    -e "s/^ \+Height: \+\([0-9]\+\).*/h=\1/p" )

ffmpeg -f x11grab -v warning -s "$w"x"$h" -i :0.0+"$x","$y" -r 10 -y $giftmp
gifsicle --optimize=3 --delay=3 $giftmp > ~/Pictures/Gifs/"$1".gif
