#!/bin/sh

NUM="$(mpc playlist -f '%position% - %artist% : %title%' | dmenu -b -p 'Play:' -fn '-*-profont-medium-*-*-*-10-*-*-*-*-*-*-*' -nb '#000000' -nf '#DDD' -sf '#FF006B' -sb '#000' | awk {'print $1'})"

if [ -z "$NUM" ]; then
	echo 'NULL'
else
	mpc play $NUM
fi
