#!/bin/sh

echo "GIMP Palette
Name: $2
Columns: 1
#" > $2.gpl;

convert "$1" -colors 16 -depth 8 -format '%c' histogram:info:- \
    | sort --reverse --numeric-sort \
    | sed -n '/\((*)\)/ p' \
    | awk '{gsub(/\(|,|\)|:/,"")}1 {print $1, $2, $3}' \
    >> $2.gpl
