#!/bin/sh

case "$1" in
    f)
        scrot "/home/atmorojo/Pictures/Screenshots/$(date %b%d::%H%M%S).png"
        ;;
    s)
        scrot -s "/home/atmorojo/Pictures/Screenshots/$(date %b%d::%H%M%S.png)"
        ;;
esac
