#!/bin/bash
# DWM status script

tgl(){
	tgl="$(date +"%a, %d %b - %H:%M")"
	echo -e "\x05·TIME· \x01$tgl"
}

bat(){
	perc="$(acpi -b | awk '{print +$4}')"
	charge="$(acpi -b | grep "Charging")"
	online="$(acpi -V | grep "on-line")"
	full="$(acpi -b | grep 'Full')"

	if [ -z "$charge" ] && [ -z "$perc" ]; then
		echo -e "\x05·BAT· \x01no-bat"
	elif [ -z "$online" ] && [ "$perc" -le "20" ]; then
		echo -e "\x05·BAT· \x03$perc% BATTERY LOW"
	elif [ "$full" ]; then
		echo -e "\x05·BAT· \x01FULL"
	else
		echo -e "\x05·BAT· \x01$perc%"
	fi
}

vol(){
	mute=`amixer get Master | grep off`
	if [ -z $mute ]; then
		vol=`amixer get Master | grep -m 1 -o '[0-9][0-9]*%'`
		echo -e "\x05·VOL· \x01$vol"
	else
		echo -e "\x05·VOL· \x01mute"
	fi
}

mem(){
	mem=`free -m | awk '/cache:/ {printf("%dMB", $3)}'`
	echo -e "\x05·MEM· \x01$mem"
}

cpu(){
	read cpu a b c previdle rest < /proc/stat
	prevtotal=$((a+b+c+previdle))
	sleep 0.5
	read cpu a b c idle rest < /proc/stat
	total=$((a+b+c+idle))
	cpu=$((100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))
	echo -e "\x05·CPU· \x01$cpu%"
}

mpd(){
	if mpc &> /dev/null && [[ $(mpc | wc -l) != 1 ]]; then
		if [[ $(mpc | awk 'NR==2 {print $1}') == "[paused]" ]] ; then
			echo -e "\x05\uE0FE \x01$( mpc | head -1 )"
		else
			echo -e "\x05\uE0FD \x01$( mpc | head -1 )"
		fi
	fi
}

while true ; do
	xsetroot -name "$(mpd) $(cpu) $(mem) $(vol) $(bat) $(tgl) "
	sleep 1s
done &
